### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by ardissaps** [MrFantiVideo/MineGate#35]
https://paste.atlauncher.com/view/e2c81503-2bc4-4611-94c8-6114583f36c4

**Comment by MrFantiVideo** [comment]
Are you using a mod that modifies slab blocks?
I see that there is a problem with the slabs that can be covered with snow. (Adding x y z axis)

```
[14/06/2022 09:41:29 AM] Caused by: java.lang.IllegalArgumentException: Cannot set property class_2754{name=axis, clazz=class net.minecraft.class_2350$class_2351, values=[x, y, z]} as it does not exist in Block{minecraft:air}
[14/06/2022 09:41:29 AM] 	at net.minecraft.class_2688.method_11657(class_2688.java:117)
[14/06/2022 09:41:29 AM] 	at net.minecraft.class_2482.handler$gpe000$init(class_2482.java:572)
[14/06/2022 09:41:29 AM] 	at net.minecraft.class_2482.<init>(class_2482.java:37)
[14/06/2022 09:41:29 AM] 	at net.minegate.fr.moreblocks.block.SnowySlabBlock.<init>(SnowySlabBlock.java:34)
[14/06/2022 09:41:29 AM] 	at net.minegate.fr.moreblocks.block.SpreadableSlabBlock.<init>(SpreadableSlabBlock.java:20)
[14/06/2022 09:41:29 AM] 	at net.minegate.fr.moreblocks.block.GrassSlabBlock.<init>(GrassSlabBlock.java:25)
[14/06/2022 09:41:29 AM] 	at net.minegate.fr.moreblocks.block.Blocks.MinecraftBlocks(Blocks.java:4801)
[14/06/2022 09:41:29 AM] 	at net.minegate.fr.moreblocks.block.Blocks.init(Blocks.java:2984)
[14/06/2022 09:41:29 AM] 	at net.minegate.fr.moreblocks.MoreBlocks.onInitialize(MoreBlocks.java:28)
[14/06/2022 09:41:29 AM] 	at net.minecraft.class_310.md220918$lambda$init$1$6(class_310.java:6987)
[14/06/2022 09:41:29 AM] 	at net.minecraft.class_310.md220918$lambda$invoke$5$2(class_310.java:7031)
[14/06/2022 09:41:29 AM] 	... 6 more
```

**Comment by ardissaps** [comment]
The one that can mix different slab and flip slab to vertical without adding new block : 
https://www.curseforge.com/minecraft/mc-mods/rectified-slabs

Also the one that add ability to destroy only half slab :
https://www.curseforge.com/minecraft/mc-mods/kleeslabs-fabric

And log slab mod :
https://modrinth.com/mod/more-log-blocks

**Comment by MrFantiVideo** [comment]
I think it's an incompatibility with the first mod you mentioned.
