### ISSUE TITLE
can not connect to server (io.netty.handler.codec.EncoderException: String too big (was 40112 bytes encoded, max 32767)

### ISSUE THREAD

**Issue by MSandro** [MrFantiVideo/MineGate#41]
since I've added MineGate to my server and Client Modpack
I can not join my server anymore.
might not be a issue caused directly by MineGate but I am not sure how to fix it.
If I remove the mod, I can join again.
Maybe its because of too large Packets or something like that.
```
[08:37:22] [Netty Epoll Server IO #1/ERROR]: Error receiving packet 102
io.netty.handler.codec.EncoderException: String too big (was 40112 bytes encoded, max 32767)
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at net.minecraft.network.PacketByteBuf.writeString(PacketByteBuf:519) ~[?:?]
	at net.minecraft.network.PacketByteBuf.writeString(PacketByteBuf:513) ~[?:?]
	at reborncore.common.crafting.RebornRecipeType.write(RebornRecipeType.java:81) ~[RebornCore-5.2.0.jar:?]
	at reborncore.common.crafting.RebornRecipeType.write(RebornRecipeType.java:40) ~[RebornCore-5.2.0.jar:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.writeRecipe(SynchronizeRecipesS2CPacket:52) ~[?:?]
	at net.minecraft.network.PacketByteBuf.writeCollection(PacketByteBuf:131) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.write(SynchronizeRecipesS2CPacket:27) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder:45) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder:14) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar:?]
	at net.minecraft.network.ClientConnection.sendInternal(ClientConnection:214) ~[?:?]
	at net.minecraft.network.ClientConnection.method_10761(ClientConnection:206) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by booleancoercion** [comment]
@MSandro Did you solve this problem? Why was the issue closed?

**Comment by MSandro** [comment]
I can confirm the issue still remains.
I've closed it because I tought the issue is caused by my too large mod-list. I'm not sure about that, and haven't researched it further.

**Comment by MSandro** [comment]
This mod might offer a solution very soon:
https://github.com/Tfarcenim/XLPacketsFabric/issues/4
